sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: rCkzEW/6OI7ThO8anqHQHZR1Mt6r02Jf9qlFpiMdLIV41Cp/Mn8EG6inUl2RGBw5s1gzAk2vaCKxxSFQ39D+4S5tKtWZrnZXfDVgrhRZpPOlxTqGVAgGqfzrYW/tCOCJOA/CyiAbwkIzi0tSt8WulullGFKZquEnyRpIVq1/2/SDfiIO9vsTdNkGSGtwL/NONQdTG6f86NF4dbEr04bf07XtiiTeJRbXlgxHeB9uQtxb7vr8BHoPkVYFuqFd2VgDiGWLdrb4BmC6L22HuZ8kG1v7zBWk3ZRtvY2GOpFI5oHV90jIVkUV8rIzQvbUmsVMt7ENBsa0oIVXHhl6/iSQ0L/7SeVE/7pTUA/nLJTeT0LOcizBLxtx5QkJ7pIFrNTD2MS/PDvS2Bl/sYl3vdwB+JRjqDnZR7OeTzyaBxzP+uHVH1dxN17GoJ06wojnxGZeaxNfdJYVgow2ppVcHZ83JpJT/NT/SeaozVHww6+FMKMFoSsJxRpxUVd6afBeRVveWr4c88RG4EfYJY/jYMjJ0+vnIqtNFsRXB/AxspX30WocnJ/iGlHdWBsixGRdXhUpZj66LbZZ66GsLribsaamrEO76y5zIILC3gz76FroU3SywtTfs0CHaIKY41mr/GqU4H68ABrVyvhgjBpIXe8rP/ZrxxeKMXOoE5eMwpi5Y4A=}, {secure: NJ2+fMrfap10Ye20Np6ftxW12u00gr3HP6GyHnuKZcHwEUimgCCz8ilpYIfmlhJ9WxDJ2TKpZhtMYJcbK8iw5x0gl+2tsspBUnYtN5n//TTcaWPJROQ1Nw4PD84/qk6pRBu5BDsTrMiPgWWOzoR4DiMpS5T3B1a8XpUYl/C+RY16xp57bxCW7DL8EmptCaf6B1ctxDiJoD+7fPDt7vXv1veNwx7i1wTr527aAWm0J1FoXec2oikFZL0FjLieHcbJtTPd8CiOSNUDrUgFT8kyhdBV8JtLyK5IgMajAypaWClJT99NGVLQpuf2XXF/MTEOx6iGhkzjqx+82zpKzwnM36AbI3rVgVAGH3dGYpKBUOjGiWGrm/WEPAXsbA1BVVfSWC4rXs2KhfJySo3rRfTGG4Umodvy0039wIK9jMYZlcrTvglIvSS7SXLZk4v6JSYSxU4u/nEUq8cuWOCgeNXYk1XxyNjp4sUHkVh0d3r7Lf1fDHq/bPaSxnOxDbIOpMVD2mZRpYNsuSJv6LvQWexnZpEwERiD8vseWrk6DjSa4Pe+6+Rn6LW2KYRXMHX1VYo45cqNOfNu7oKbiIP+C7RPvp7Rnr7B0NGe1C4IrNsHRvIQb0/jDJPobHmafEGaUVUHWQdbDgmVZybA1072XPfHCpAorSBxNbXUE0Iy+2gAFX0=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
